# Generated by Django 5.2.4 on 2025-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
