# Generated by Django 5.2.4 on 2025-07-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidateprofile_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='sectors',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
    ]
