# Generated by Django 5.2.4 on 2025-07-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_candidateprofile_sectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='sectors',
        ),
    ]
