# Generated by Django 5.2.4 on 2025-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_candidateprofile_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='core.category'),
        ),
    ]
