# Generated by Django 5.2.4 on 2025-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidateprofile_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_job_offers', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Statistique d'utilisation",
                'verbose_name_plural': "Statistiques d'utilisation",
            },
        ),
    ]
